/**
 * Created by Ascarbek on 01.12.2015.
 */
(function() {
    'use strict';

    angular
        .module('demo', ['azSuggestBox'])
        .controller('demo', ['$scope', '$element', '$timeout', function($scope, $element, $timeout) {
            var vm = this;

            // generated by http://www.theonegenerator.com/
            vm.names = [{
                    "name": "Reese Witherspoon",
                    "email": "reese.witherspoon@arcu.com",
                    "lorem": "Lorem ipsum dolor sit amet consectetur. Condimentum id venenatis a. Ullamcorper dignissim cras.",
                    "cc": "4556148356219995"
                },
                {
                    "name": "Ariana Grande",
                    "email": "ariana_grande@in.com",
                    "lorem": "Neque ornare aenean euismod elementum. A scelerisque purus. Et pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
                    "cc": "4370806281261747"
                },
                {
                    "name": "Ricky Whittle",
                    "email": "ricky.whittle@ullamcorper.com",
                    "lorem": "Ullamcorper sit amet risus nullam. Nibh mauris cursus mattis molestie a iaculis at erat. Euismod nisi porta lorem. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Egestas diam in.",
                    "cc": "4716019748787857"
                },
                {
                    "name": "Vera Farmiga",
                    "email": "vera.farmiga@et.com",
                    "lorem": "Lobortis mattis aliquam faucibus purus in massa. Cursus sit amet dictum sit amet. Lectus quam id leo. Egestas diam in arcu cursus. Viverra adipiscing at in tellus integer feugiat scelerisque varius.",
                    "cc": "4716356736698476"
                },
                {
                    "name": "Helena Bonham Carter",
                    "email": "helena_bonham_carter@cras.com",
                    "lorem": "Tempor nec feugiat nisl pretium fusce id velit ut. Mi sit amet mauris commodo quis imperdiet massa tincidunt. Nulla facilisi nullam vehicula ipsum a arcu cursus.",
                    "cc": "4539987881980361"
                },
                {
                    "name": "Cobie Smulders",
                    "email": "cobie_smulders@quis.com",
                    "lorem": "Risus feugiat in ante metus dictum at tempor commodo ullamcorper. Eros in cursus turpis massa tincidunt dui ut ornare lectus. Nisl condimentum id venenatis a. Duis at tellus at urna. Blandit aliquam etiam erat velit. Adipiscing enim eu turpis egestas pretium.",
                    "cc": "4716483910252886"
                },
                {
                    "name": "Elizabeth Olsen",
                    "email": "elizabetholsen@in.com",
                    "lorem": "At in tellus integer feugiat scelerisque varius morbi enim nunc. Odio ut enim blandit. Eget velit aliquet sagittis id consectetur.",
                    "cc": "4716854291468632"
                },
                {
                    "name": "Lea Michele",
                    "email": "lea.michele@lacinia.com",
                    "lorem": "Urna porttitor rhoncus dolor purus non enim praesent elementum. Nullam vehicula ipsum a. Porta nibh venenatis cras sed felis eget. Congue eu consequat ac felis donec et odio pellentesque.",
                    "cc": "4716781714726454"
                },
                {
                    "name": "Elizabeth Henstridge",
                    "email": "elizabeth.henstridge@tempor.com",
                    "lorem": "Eget nullam non nisi est. Varius quam quisque id diam vel quam. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor. Eget velit aliquet sagittis. Vitae suscipit tellus mauris a diam maecenas sed.",
                    "cc": "4532136002790104"
                },
                {
                    "name": "Nicholas Hoult",
                    "email": "nicholashoult@ut.com",
                    "lorem": "Enim nec dui nunc mattis enim ut. Elit sed vulputate. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Sem fringilla ut morbi.",
                    "cc": "4716038624177702"
                },
                {
                    "name": "Gareth Edwards",
                    "email": "gareth_edwards@etiam.com",
                    "lorem": "Fames ac turpis egestas sed tempus. Lobortis feugiat vivamus at. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Mauris augue neque gravida in fermentum et sollicitudin.",
                    "cc": "4485092505895089"
                },
                {
                    "name": "Alexander Ludwig",
                    "email": "alexander.ludwig@urna.com",
                    "lorem": "Quam adipiscing vitae proin sagittis nisl rhoncus mattis. Fermentum dui faucibus in. Sollicitudin nibh sit amet. Neque egestas congue quisque egestas diam.",
                    "cc": "4539619624870498"
                },
                {
                    "name": "Kate Beckinsale",
                    "email": "katebeckinsale@velit.com",
                    "lorem": "Ultrices tincidunt arcu non sodales neque sodales ut. Quis hendrerit dolor. Augue lacus viverra vitae congue eu consequat ac felis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Vulputate enim nulla aliquet.",
                    "cc": "4532850893004744"
                },
                {
                    "name": "Penélope Cruz",
                    "email": "penelope.cruz@turpis.com",
                    "lorem": "Urna nunc id cursus. Mus mauris vitae ultricies leo. Netus et malesuada fames ac turpis egestas integer eget aliquet.",
                    "cc": "4024007135279577"
                },
                {
                    "name": "Katherine Heigl",
                    "email": "katherine.heigl@hendrerit.com",
                    "lorem": "Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Nisl nisi scelerisque eu. Id cursus metus aliquam eleifend. Sit amet venenatis urna cursus. Libero nunc consequat interdum varius sit. In hac habitasse.",
                    "cc": "4985646002274588"
                },
                {
                    "name": "Halle Berry",
                    "email": "halle.berry@arcu.com",
                    "lorem": "At quis risus sed vulputate odio ut enim blandit volutpat. Arcu dictum varius duis. Facilisis mauris sit amet massa vitae tortor condimentum. Sit amet consectetur adipiscing elit duis.",
                    "cc": "4916105903476010"
                },
                {
                    "name": "Manu Bennett",
                    "email": "manu.bennett@sit.com",
                    "lorem": "At augue eget arcu. Dignissim suspendisse in est ante in nibh mauris. Feugiat vivamus at augue eget arcu dictum. Et netus et malesuada fames ac turpis egestas integer. Purus non enim praesent elementum facilisis leo vel fringilla est.",
                    "cc": "4929312828119320"
                },
                {
                    "name": "Ralph Waite",
                    "email": "ralphwaite@nibh.com",
                    "lorem": "Tellus molestie nunc non blandit massa. Sed id semper risus in hendrerit gravida rutrum. Consectetur adipiscing elit duis tristique sollicitudin nibh. Diam vulputate ut pharetra. Nulla pharetra diam sit amet nisl suscipit adipiscing.",
                    "cc": "4552860164118904"
                },
                {
                    "name": "Jim Carrey",
                    "email": "jim_carrey@eu.com",
                    "lorem": "Vitae et leo duis ut diam quam. In eu mi bibendum. Cras fermentum odio. Amet risus nullam eget felis. In nisl nisi scelerisque eu. Enim tortor at auctor.",
                    "cc": "4556845956627846"
                },
                {
                    "name": "Rachel Nichols",
                    "email": "rachel_nichols@ornare.com",
                    "lorem": "Tempor id eu. Amet mattis vulputate enim nulla aliquet porttitor lacus. Ipsum dolor sit amet consectetur adipiscing elit duis tristique. Egestas tellus rutrum tellus. Amet nulla facilisi morbi tempus iaculis urna id. Congue mauris rhoncus aenean.",
                    "cc": "4916292685272864"
                },
                {
                    "name": "Brie Larson",
                    "email": "brie.larson@viverra.com",
                    "lorem": "Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Nullam vehicula ipsum a arcu. Mi quis hendrerit. Mauris pellentesque pulvinar pellentesque habitant. Vulputate eu scelerisque felis imperdiet proin fermentum leo. Vitae et leo duis ut diam quam nulla porttitor.",
                    "cc": "4539892106920269"
                }
            ];

            vm.cities = [{
                    name: 'Beijing',
                    population: 20693000,
                    country: 'China'
                },
                {
                    name: 'Tokyo',
                    population: 13189000,
                    country: 'Japan'
                }
            ];

            vm.model1 = [];
            $timeout(function() {
                vm.model1.push(vm.names[1]);
                vm.model1.push({
                    name: "Cobie Smulders"
                });
            }, 100);

            //vm.indexes2 = [0];
            vm.model2 = [{
                "name": "Cobie Smulders"
            }];


            vm.model = [{
                name: 'Tokyo',
                population: 13189000,
                country: 'Japan'
            }, {
                name: 'London',
                population: 8630100,
                country: 'United Kingdom'
            }];

            vm.onChange1 = function() {
                console.log('Change');
            }

            vm.clickTest = function(name) {
                alert('You clicked on: ' + name);
            }
        }]);
})();
